### ISSUE TITLE
Official permission from Digital Extremes required

### ISSUE THREAD

**Issue by Friendly0Fire** [cephalon-sofis/warframe_api#1]
In the current context, using this API would be against the terms of the mobile app and the game itself. This means that, by logging in using this wrapper, you risk getting your account banned (and good luck getting support to unban you).

I would advise to only use the parts that do not require authentication.

**Comment by ScottKaye** [comment]
I can confirm this - I was in the process of porting this to Node.js, and my account has been suspended for a (very fortunate) 2 days.  It was foolish to test it on my real account, but I can totally see why DE wants to lock this down.

From the EULA, §2.b

>  _You agree that you will not, under any circumstances_ [...] reverse engineer, decompile, disassemble or otherwise derive source code or game data from the Software or reduce the Software to a human-readable form, except to the extent that such actions are expressly permitted by applicable law

There are a ton of reasons why DE may never open the private API.  The biggest one is security.  A third-party developer implementing a real Warframe login on their website to get real account information cannot be trusted.  This is because DE cannot enforce any sort of **liability** on that web developer when dealing with this method of API access.

The only way I can see this happening is if DE implements OAuth or a similar token-based system.  It's a lot of work on their end that earns them $zero in return, so this likely won't happen.

As for my port, it was purely intended to be private.  I actually planned on sending DE an email this morning to request permission and ask for a way to sign my requests.  My goal was to create an automatic spreadsheet of my stuff that would help me track Mastery Rank and help determine which items to buy next.  I will not continue development on it.

As a warning to anybody reading this; while this is a cool project to read through, I recommend against actually running it and authenticating.  I got lucky with a 2 day ban, but your mileage may vary.
